name: auto-label-new-issues

on:
  issues:
    types: [opened]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Label new issues with 'needs-triage'
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "needs-triage"